version: "3.9"
services:
  rediscache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - cbnet
  app:
    build: .
    restart: on-failure:5
    depends_on:
      - rediscache
    networks:
      - cbnet
  nginxproxy:
    build: ./nginx
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - cbnet

networks:
  cbnet:
    driver: bridge
